config/routes.rb
Rails.application.routes.draw do

  resources :games

  namespace :admin do
    root 'welcome#index'
    get 'users' => 'users#index'
    get 'users/:id' => 'users#show'
    get 'users/:id/edit' => 'users#edit'
    patch 'users/:id/edit' => 'users#update'
    delete 'users/:id/' => 'users#update'
  end

  get 'register' => 'registrations#new'
  post 'register' => 'registrations#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'me' => 'me#index'

  root 'welcome#index'
  get 'tos' => 'welcome#tos'
  get 'policy' => 'welcome#policy'
  get 'about' => 'welcome#about'

  get 'test' => 'welcome#test'
  resources :getopis

end

app/models/getopi.rb
class Getopi
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
end

app/controllers/getopis_controller.rb
class GetopisController < ApplicationController
  before_action :set_getopi, only: [:show, :edit, :update, :destroy]

  # GET /getopis
  # GET /getopis.json
  def index
    @getopis = Getopi.all
  end

  # GET /getopis/1
  # GET /getopis/1.json
  def show
  end

  # GET /getopis/new
  def new
    @getopi = Getopi.new
  end

  # GET /getopis/1/edit
  def edit
  end

  # POST /getopis
  # POST /getopis.json
  def create
    @getopi = Getopi.new(getopi_params)

    respond_to do |format|
      if @getopi.save
        format.html { redirect_to @getopi, notice: 'Getopi was successfully created.' }
        format.json { render :show, status: :created, location: @getopi }
      else
        format.html { render :new }
        format.json { render json: @getopi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /getopis/1
  # PATCH/PUT /getopis/1.json
  def update
    respond_to do |format|
      if @getopi.update(getopi_params)
        format.html { redirect_to @getopi, notice: 'Getopi was successfully updated.' }
        format.json { render :show, status: :ok, location: @getopi }
      else
        format.html { render :edit }
        format.json { render json: @getopi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /getopis/1
  # DELETE /getopis/1.json
  def destroy
    @getopi.destroy
    respond_to do |format|
      format.html { redirect_to getopis_url, notice: 'Getopi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_getopi
      @getopi = Getopi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def getopi_params
      params.require(:getopi).permit(:title, :description)
    end
end

app/helpers/getopis_helper.rb
module GetopisHelper
end

app/views/getopis/_form.html.haml
= form_for @getopi do |f|
  - if @getopi.errors.any?
    #error_explanation
      %h2= "#{pluralize(@getopi.errors.count, "error")} prohibited this getopi from being saved:"
      %ul
        - @getopi.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/getopis/edit.html.haml
%h1 Editing getopi

= render 'form'

= link_to 'Show', @getopi
\|
= link_to 'Back', getopis_path

app/views/getopis/index.html.haml
%h1 Listing getopis

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @getopis.each do |getopi|
    %tr
      %td= getopi.title
      %td= getopi.description
      %td= link_to 'Show', getopi
      %td= link_to 'Edit', edit_getopi_path(getopi)
      %td= link_to 'Destroy', getopi, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Getopi', new_getopi_path

app/views/getopis/new.html.haml
%h1 New getopi

= render 'form'

= link_to 'Back', getopis_path

app/views/getopis/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @getopi.title
%p
  %b Description:
  = @getopi.description

= link_to 'Edit', edit_getopi_path(@getopi)
\|
= link_to 'Back', getopis_path